# Generated by Django 4.2.7 on 2023-11-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosModels',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao_curta', models.TextField(max_length=255, verbose_name='Descrição curta')),
                ('descricao_longa', models.TextField(max_length=255, verbose_name='Descrição longa')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto_imagem/%Y/%m/', verbose_name='Imagem')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('preco_marketing', models.FloatField(verbose_name='Preço marketing')),
                ('preco_marketing_promocional', models.FloatField(verbose_name='Preço marketing promocional')),
                ('tipo', models.CharField(choices=[('KG', 'Kilo'), ('UN', 'Unidade'), ('PC', 'Pacote'), ('DY', 'Display'), ('FD', 'Fardo')], default='KG', max_length=2, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'indexes': [models.Index(fields=['codigo'], name='codigo_produto_idx')],
            },
        ),
    ]
