# Generated by Django 4.2.7 on 2023-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao_curta', models.TextField(max_length=255, verbose_name='Descrição curta')),
                ('descricao_longa', models.TextField(max_length=255, verbose_name='Descrição longa')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto_imagem/%Y/%m/', verbose_name='Imagem')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('preco_marketing', models.FloatField(verbose_name='Preço marketing')),
                ('preco_marketing_promocional', models.FloatField(verbose_name='Preço marketing promocional')),
                ('tipo', models.CharField(choices=[('KG', 'Kilo'), ('UN', 'Unidade'), ('PC', 'Pacote'), ('DY', 'Display'), ('FD', 'Fardo')], default='KG', max_length=2, verbose_name='Tipo')),
            ],
        ),
    ]
