# Generated by Django 4.2.7 on 2023-11-28 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariacaoProdutosModel',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código variação')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome variação')),
                ('preco', models.FloatField(verbose_name='Preço variação')),
                ('preco_promocional', models.FloatField(default=0, verbose_name='Preço promocional variação')),
                ('estoque', models.PositiveIntegerField(default=1, verbose_name='Estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produtosmodels', verbose_name='Produto variação')),
            ],
            options={
                'verbose_name': 'Produto variação',
                'verbose_name_plural': 'Produtos variações',
                'indexes': [models.Index(fields=['codigo'], name='codigo_produto_variacao_idx')],
            },
        ),
    ]
