# Generated by Django 4.2.7 on 2023-12-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_variacaoprodutosmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosmodels',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
