# Generated by Django 4.2.7 on 2023-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produtosmodels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosmodels',
            name='descricao_longa',
            field=models.TextField(max_length=2000, verbose_name='Descrição longa'),
        ),
    ]
