# Generated by Django 4.2.7 on 2023-12-01 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilmodels',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
